const colors = {
  light: {
    text: '#1C1C1E',
    tint: '#2D5BFF',
    background: '#F7F7F8',
    foreground: '#1C1C1E',
    card: '#FFFFFF',
    cardForeground: '#1C1C1E',
    primary: '#2D5BFF',
    primaryForeground: '#FFFFFF',
    secondary: '#F0F0F2',
    secondaryForeground: '#1C1C1E',
    muted: '#F0F0F2',
    mutedForeground: '#8E8E93',
    accent: '#EEF1FF',
    accentForeground: '#2D5BFF',
    destructive: '#FF3B30',
    destructiveForeground: '#FFFFFF',
    border: '#E5E5EA',
    input: '#E5E5EA',
    success: '#34C759',
    warning: '#FF9500',
    urgentSoft: '#FFF0EF',
    successSoft: '#ECF9EF',
    warningSoft: '#FFF5E8',
  },
  dark: {
    text: '#FFFFFF',
    tint: '#7A92FF',
    background: '#000000',
    foreground: '#FFFFFF',
    card: '#1C1C1E',
    cardForeground: '#FFFFFF',
    primary: '#5D79FF',
    primaryForeground: '#FFFFFF',
    secondary: '#2C2C2E',
    secondaryForeground: '#FFFFFF',
    muted: '#2C2C2E',
    mutedForeground: '#98989D',
    accent: '#232D60',
    accentForeground: '#AAB8FF',
    destructive: '#FF453A',
    destructiveForeground: '#FFFFFF',
    border: '#38383A',
    input: '#38383A',
    success: '#30D158',
    warning: '#FF9F0A',
    urgentSoft: '#3A1F1D',
    successSoft: '#183221',
    warningSoft: '#3A2B16',
  },
  radius: 16,
} as const;

export type ThemeColors = typeof colors.light;
export type Appearance = 'system' | 'light' | 'dark';
export default colors;
