const colors = {
  light: {
    text: '#302720',
    tint: '#A34F2B',
    background: '#F7F3EC',
    foreground: '#302720',
    card: '#FFFDFA',
    cardForeground: '#302720',
    primary: '#A34F2B',
    primaryForeground: '#FFFDFA',
    secondary: '#EEE7DD',
    secondaryForeground: '#40342C',
    muted: '#EEE7DD',
    mutedForeground: '#76685D',
    accent: '#F3E4D5',
    accentForeground: '#A34F2B',
    destructive: '#C74643',
    destructiveForeground: '#FFFDFA',
    border: '#E5DACE',
    input: '#E5DACE',
    success: '#248A63',
    warning: '#B97018',
    urgentSoft: '#FCEAE9',
    successSoft: '#E6F3ED',
    warningSoft: '#FAF0E2',
  },
  dark: {
    text: '#F7F3EC',
    tint: '#ECAA80',
    background: '#181411',
    foreground: '#F7F3EC',
    card: '#241E19',
    cardForeground: '#F7F3EC',
    primary: '#ECAA80',
    primaryForeground: '#302014',
    secondary: '#342B24',
    secondaryForeground: '#F5EDE2',
    muted: '#342B24',
    mutedForeground: '#BBAE9F',
    accent: '#3E2B1E',
    accentForeground: '#F0BF9B',
    destructive: '#F17670',
    destructiveForeground: '#FFFDFA',
    border: '#493D32',
    input: '#493D32',
    success: '#58B891',
    warning: '#E4A652',
    urgentSoft: '#3A2425',
    successSoft: '#1C332B',
    warningSoft: '#382C1C',
  },
  radius: 20,
} as const;

export type ThemeColors = { [Key in keyof typeof colors.light]: string };
export type Appearance = 'system' | 'light' | 'dark';
export default colors;
